services:
  mysql-dailyfeed:
    image: mysql:8.0.38-debian
    platform: linux/amd64  # ARM64 호환성을 위한 플랫폼 지정
    restart: always
    #    command: --lower_case_table_names=1
    container_name: mysql-dailyfeed
    hostname: mysql-dailyfeed
    ports:
      - "23306:3306"
    environment:
      - MYSQL_USER=dailyfeed
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=hitEnter!!!
      - MYSQL_DATABASE=dailyfeed
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=hitEnter!!!
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
  mongo-dailyfeed-1:
    image: mongo:7.0
    container_name: mongo_dailyfeed_1
    hostname: mongo_dailyfeed_1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-dailyfeed-1-data:/data/db
    networks:
      mongo-cluster:
        aliases:
          - mongo_dailyfeed_1
  mongo-dailyfeed-2:
    image: mongo:7.0
    container_name: mongo_dailyfeed_2
    hostname: mongo_dailyfeed_2
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-dailyfeed-2-data:/data/db
    networks:
      mongo-cluster:
        aliases:
          - mongo_dailyfeed_2
  mongo-dailyfeed-3:
    image: mongo:7.0
    container_name: mongo_dailyfeed_3
    hostname: mongo_dailyfeed_3
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-dailyfeed-3-data:/data/db
    networks:
      mongo-cluster:
        aliases:
          - mongo_dailyfeed_3
  # Replica Set 초기화를 위한 임시 컨테이너
  mongo-setup:
    image: mongo:7.0
    container_name: mongo_setup
    depends_on:
      - mongo-dailyfeed-1
      - mongo-dailyfeed-2
      - mongo-dailyfeed-3
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "bash", "/scripts/init-replica.sh" ]
    networks:
      - mongo-cluster
  redis-dailyfeed:
    image: redis:7.0
    command: redis-server --port 6379
    hostname: redis-dailyfeed-localhost
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 26379:6379
    depends_on: 
      - redis-dailyfeed-commander
    links:
      - redis-dailyfeed-commander
  redis-dailyfeed-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander-localhost
    restart: always
    environment:
      - REDIS_HOSTS=redis-dailyfeed-localhost
    ports:
      - 38081:8081
volumes:
  mongo-dailyfeed-1-data:
  mongo-dailyfeed-2-data:
  mongo-dailyfeed-3-data:

networks:
  mongo-cluster:
    driver: bridge