apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailyfeed-timeline
  labels:
    app: dailyfeed-timeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dailyfeed-timeline
  template:
    metadata:
      labels:
        app: dailyfeed-timeline
    spec:
      containers:
      - name: timeline
        image: alpha300uk/dailyfeed-timeline-svc:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dailyfeed-timeline-service
spec:
  selector:
    app: dailyfeed-timeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer