apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: istio-system
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31003
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: grafana
