apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: istio-system
spec:
  type: NodePort
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 31001
    protocol: TCP
    name: http-query
  selector:
    app: jaeger