apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: istio-system
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 31002
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: prometheus