apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb