apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: infra
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: mongodb
    spec:
      initContainers:
      - name: init-replica-set
        image: mongo:7.0
        command:
        - /bin/sh
        - -c
        - |
          cat > /docker-entrypoint-initdb.d/00-init-replica.js <<'EOF'
          try {
            rs.initiate({
              _id: 'rs0',
              members: [{ _id: 0, host: 'mongodb.infra.svc.cluster.local:27017' }]
            });
          } catch(e) {
            print('Replica set already initialized or error: ' + e);
          }
          EOF
        volumeMounts:
        - name: mongodb-init-rs
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: mongodb
        image: mongo:7.0
        command:
        - mongod
        - "--replSet"
        - "rs0"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "hitEnter###"
        - name: MONGO_INITDB_DATABASE
          value: "dailyfeed"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-init
          mountPath: /docker-entrypoint-initdb.d/01-users.js
          subPath: init.js
        - name: mongodb-init-rs
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: mongodb-data
        emptyDir: {}
      - name: mongodb-init
        configMap:
          name: mongodb-init-script
      - name: mongodb-init-rs
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: infra
data:
  init.js: |
    db = db.getSiblingDB('dailyfeed');
    db.createUser({
      user: 'dailyfeed',
      pwd: 'hitEnter###',
      roles: [
        { role: 'readWrite', db: 'dailyfeed' },
        { role: 'dbAdmin', db: 'dailyfeed' }
      ]
    });
    db.createUser({
      user: 'dailyfeed-search',
      pwd: 'hitEnter###',
      roles: [
        { role: 'readWrite', db: 'dailyfeed' },
        { role: 'dbAdmin', db: 'dailyfeed' }
      ]
    });
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb