apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql