apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: infra
data:
  MONGODB_HOST: "mongodb.infra.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "dailyfeed"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: infra
type: Opaque
stringData:
  MONGODB_CONNECTION_URI: "mongodb://dailyfeed:hitEnter###@mongodb.infra.svc.cluster.local:27017/dailyfeed"
  MONGODB_USERNAME: "dailyfeed"
  MONGODB_PASSWORD: "hitEnter###"
