apiVersion: v1
kind: Service
metadata:
  name: dailyfeed-timeline-debug-svc
  namespace: dailyfeed
  labels:
    app: dailyfeed-timeline
    purpose: debug
spec:
  type: NodePort
  ports:
  - port: 8080          # Service port
    targetPort: 8080    # Container port (dailyfeed-timeline app이 리스닝하는 포트)
    nodePort: 30890     # Node port - KIND cluster.yml의 extraPortMappings와 일치해야 함
    protocol: TCP
    name: http
  selector:
    app: dailyfeed-timeline  # Pod selector (실제 Pod의 label과 일치해야 함)
