apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: infra
  labels:
    app: mongodb
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb