apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  namespace: infra
  labels:
    app: mysql
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
      name: mysql
  selector:
    app: mysql