apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: infra
  labels:
    app: redis
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis