services:
  mysql-dailyfeed:
    image: mysql:8.0.38-debian
    platform: linux/amd64  # ARM64 호환성을 위한 플랫폼 지정
    restart: always
    #    command: --lower_case_table_names=1
    container_name: mysql-dailyfeed
    hostname: mysql-dailyfeed
    ports:
      - "23306:3306"
    environment:
      - MYSQL_USER=dailyfeed
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=pressF5!!!
      - MYSQL_DATABASE=dailyfeed
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=pressF5!!!
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/